/// Flutter icons One_Roof
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  One_Roof
///      fonts:
///       - asset: fonts/One_Roof.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class One_Roof {
  One_Roof._();

  static const _kFontFam = 'One_Roof';
  static const String _kFontPkg = null;

  static const IconData profile_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
